### PR TITLE
Removed numpy dependency

### PR DESCRIPTION
**Pull request by martinbrose**
Addresses feature request #13.

- #13

### CODE REVIEW

**Comment by tevslin** [comment]
I appreciate the work. am reluctant to have the extra code but will merge if there is no other way to avoid a huge docker image size

**Comment by martinbrose** [comment]
I think you're totally right... there are better options.

I'll replace the code for median and mean with the built-in statistics module.
Let me research if there is an alternative for the percentile calculation.

**Comment by martinbrose** [comment]
I agree, it's not ideal. 
My proposed change is born out of desperation. Every time I change the container base image, I experience a long build of the numpy wheel. Also, the automatic build of my Dropbox containers on GitHub usually fails due to timeouts.
Plus, installing numpy adds approximately 100MB to my docker image, which is quite a lot for just using the percentile function.

Unfortunately, I couldn't find another small package that offers the percentile functionality exactly like numpy.

The standards `statistics` package offers `quantiles`, which seemed like a great candidate:
```
Signature: statistics.quantiles(data, *, n=4, method='exclusive')
Docstring:
Divide *data* into *n* continuous intervals with equal probability.

Returns a list of (n - 1) cut points separating the intervals.

Set *n* to 4 for quartiles (the default).  Set *n* to 10 for deciles.
Set *n* to 100 for percentiles which gives the 99 cuts points that
separate *data* in to 100 equal sized groups.
```
`statistics.quantiles(data, n=10)[8]` looked like a great substitution, but for some reason the output differs quite a bit from what numpy would return, as shown in this example:
```python
data = [123, 234, 345, 456, 567, 678, 789, 1011, 1112, 1213, 1314]
quantiles = statistics.quantiles(data, n=10)

print(quantiles)
[145.2, 278.4, 411.6, 544.8, 678.0, 833.4, 1051.4, 1172.6, 1293.8]

print(quantiles[8])
1293.8

round(np.percentile(data,90),2)
1213.0
```
The logic is different, whereas numpy returns the 10th element of a 11-element as a result, statistics.quantiles does not.
I have to use a list of 9 elements, for statistics.quantiles to return one of the elements as the result. Most likely because it uses 0 as the first element? See this example:
```python
data = [123, 234, 345, 456, 567, 678, 789, 1011, 1112]
quantiles = statistics.quantiles(data, n=10)

print(quantiles)
[123.0, 234.0, 345.0, 456.0, 567.0, 678.0, 789.0, 1011.0, 1112.0]
```

The Numpy default setting for percentile is a linear interpolation method:
https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

To make my proposed code reconcilable to Stackoverflow, I found and used the solution here:
https://stackoverflow.com/questions/2374640/how-do-i-calculate-percentiles-with-python-numpy
Changing the variable names and removing the need to provide sorted data.

And to address your potential concerns that my function `calculate_percentile()` produces different results to `np.percentile()`, I have created a few tests here:

```python
import numpy as np
from cloudflarepycli.cloudflareclass import cloudflare

cf = cloudflare()

data = [123, 234, 345, 456, 567, 678, 789]
assert(round(cf.calculate_percentile(data,90),2) == round(np.percentile(data,90),2))

# Percentile should return the 90% element in the list
data = [123, 234, 345, 456, 567, 678, 789, 1011, 1112, 1213, 1314]
assert(round(cf.calculate_percentile(data,90),2) == round(np.percentile(data,90),2))
assert(round(np.percentile(data,90),2) == 1213)
assert(round(cf.calculate_percentile(data,90),2) == 1213)

# Testing some unsorted data lists
data = [123, 345, 234, 789, 456, 567, 678]
assert(round(cf.calculate_percentile(data,90),2) == round(np.percentile(data,90),2))

data = [789, 123, 234, 1112, 345, 456, 1213, 567, 678, 1011, 1314]
assert(round(cf.calculate_percentile(data,90),2) == round(np.percentile(data,90),2))

# Testing a data list resembling speed test results
data = [350.43, 363.76, 321.23, 309.76, 335.89]
assert(round(cf.calculate_percentile(data,90),2) == round(np.percentile(data,90),2))
```

**Comment by tevslin** [comment]
Martin, thank you not only for the changes but for your careful testing

**Comment by martinbrose** [comment]
Tom, many thanks for accepting and merging these changes!

**Pull request merged**
