### PR TITLE
Introduced context manager for Non-Windows OS

### LINKED ISSUE #1: Breaking change for Linux with introduction of the wres package
Thanks for writing this little helper class for the cloudflare speedtest.

I received the following error when I tried to use it on a Mac:
```
Traceback (most recent call last):
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/bin/cfspeedtest", line 8, in <module>
    sys.exit(main())
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/__main__.py", line 35, in main
    thedict=thetester.runalltests()
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/cloudflareclass.py", line 154, in runalltests
    fulltimes,servertimes,requesttimes=self.download(1,self.latencyreps) #measure latency and jitter
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/cloudflarepycli/cloudflareclass.py", line 101, in download
    import wres  
  File "/Users/martinbrose/opt/anaconda3/envs/speedtest/lib/python3.9/site-packages/wres/__init__.py", line 16, in <module>
    ntdll = ctypes.WinDLL('NTDLL.DLL')
AttributeError: module 'ctypes' has no attribute 'WinDLL'
```
I think you introduced a Windows DLL dependency in commit 841f4525cbcf522a0290cb823d3312bdacf9b5c6 when you added `import wres`. Was this intentional?

Your PyPI version 1.0.3 works fine, but version 1.6.0 won't run on Linux machines.

### PR DESCRIPTION
**Pull request by martinbrose**
Closes #1

### CODE REVIEW

**Comment by martinbrose** [comment]
Just bumping as it would be nice to re-gain functionality for Mac/Linux in future versions.

**Comment by tevslin** [comment]
Martin,

 

Sorry for the delay. Had health issues so out of the loop for a while but now will get back to work on this. Thank you for your contributions.

 

Tom

**Comment by tevslin** [comment]
Finally merged. Thank you, Martin

**Comment by martinbrose** [comment]
Hi @tevslin,

hope you're feeling better. Apologies for my slow response, I am unfortunately rather busy at work currently.

Thank for merging and closing the pull request!

I tried to run version 1.7.0 (from PyPI) on my Linux based machines and encountered problems.
I'll probably raise another pull request once I had the time to see what the problem is.

**Pull request merged**
